### ISSUE TITLE
replace vnode process name atom generation with gproc?

### ISSUE THREAD

**Issue by yrashk** [basho/riak_core#156]
Hi,

Have you considered using gproc instead of generating atoms like `proxy_my_vnode_319703483166135013357056057156686910549735243776`? With gproc, you can register those processes as {vnode_proxy, 319703483166135013357056057156686910549735243776}. With gproc you also get some additional features like being able to await for a registration and such.

I have been using gproc in almost every project and it has proven to be incredibly useful.

**Comment by jonmeredith** [comment]
Hi Yuri,

I'm not sure gproc will do what we need for this.  

The point of the registered name on the proxy processes is so that we can send distributed erlang requests to a specific process, on a remote node.  The call ends up being

```
    gen_fsm:send_event({ProxyRegName, Node}, Req).
```

Doing things this way allows us to avoid having a single named process on Node that has to farm out the requests to the individual vnodes (which is what the vnode_master processes used to do pre-1.1).

From what I remember of gproc it couldn't do this for us - as handy as it is for name registration inside a node.

**Comment by yrashk** [comment]
Jon,

Very good point, indeed. This tradeoff is clear to me now. I strongly suspect I was reading that part way before 1.1.

Thanks!
