### ISSUE TITLE
Riak take a *lot* longer to start up on systems with ulimit set to a million. (centos/vagrant/virtualbox)

### ISSUE THREAD

**Issue by simonvc** [basho/riak_core#308]
Riak take a _lot_ longer to start up on under virtualbox with ulimit set to a million. (centos/vagrant/virtualbox)

Ping me for the vagrant gist (i cant post it here.)

[vagrant@localhost riak-ee]$ ulimit -n 1000000
[vagrant@localhost riak-ee]$ time dev1/bin/riak start
        real    1m18.837s
        user    0m1.167s
        sys 0m26.828s

[vagrant@localhost riak-ee]$ ulimit -n 4096
[vagrant@localhost riak-ee]$ time dev1/bin/riak start
        real    0m2.330s
        user    0m0.833s
        sys 0m0.066s
[vagrant@localhost riak-ee]$

**Comment by evanmcc** [comment]
I am pretty sure that this is a linux issue rather than a riak issue.  I am guessing that the fd pool is a per-process statically allocated thing, so making it big is going to add to memory pressure and kernel operations.  I can see this making things pretty unhappy on a wimpy-enough VM.  On a machine with plenty of RAM, it doesn't change anything.
