### ISSUE TITLE
Transfers in the ring will stuck in the 'awaiting' state in a cluster of vnode-less applications.

### ISSUE THREAD

**Issue by sumerman** [basho/riak_core#403]
Found this behaviour accidentally while testing data provider with sharding piggybacked on riak's APLs (for co-location with storage) when actual storage was shutdown.
1. start `node1` with vnode-less `riak_core`-based application
2. start `node2`, then join it to the `node1`
3. there will be `awaiting` transfers for `[]` list of vnodes in the ring's state
4. preflists will not be updated 

Apparently claimant will transfer ownership only for `completed` transfers (without looking into the list of vnodes) and transfer may be marked as `completed` only inside `transfer_complete` which will not be called since there are no vnodes.

Currently I've solved my issue by including mock-vnodes into the data provider app. Is there a more elegant solution?

**Comment by jrwest** [comment]
@sumerman `riak_core` applications typically use vnodes and in several places, like the claimant, there are  assumptions like the one you have found. A quick fix could be (note, i haven't tried this myself) to modify the claimant's planning code to immediately mark the handoff's as complete -- granted this would require a fork/patch vs. just plugging into the vnode behaviour. Unfortunately, since this isn't as common of a use-case I don't think we will be making a change to support this, directly. However, patches are always accepted if you find a nice way to make both work (perhaps via application env?).

I'm going to close this issue since there has been some ongoing house-keeping in this repo. Please feel free to re-open if needed.

**Comment by sumerman** [comment]
@jrwest thanks for your reply. I believe this behaviour is ok, but the whole `claimant` thing worth mentioning the way it is done for ring resizing.

**Comment by jrwest** [comment]
@sumerman I'm not entirely sure I understand your note about ring resizing. Would you mind clarifying? If you are wondering if the same changes are necessary for the resizing code path, they would be only if you plan to use that feature -- otherwise that code will not run.

**Comment by sumerman** [comment]
@jrwest I meant there is `docs/ring-resizing.md` which states pretty clear what happens upon resizing, so maybe there should be one more `.md` file which would elaborate on `claimant`/`ring`/ `transfers` interactions.

**Comment by jrwest** [comment]
@sumerman ah, agreed. documentation is one area that is lacking. what we have is also fragmented: there is some more info [here](https://github.com/basho/riak_core/wiki#wiki-handoffs) and [here](https://github.com/basho/riak_core/wiki/Handoffs)
